Jun-03 19:19:42.181 [main] DEBUG nextflow.cli.Launcher - $> nextflow run test.nf
Jun-03 19:19:42.272 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.2
Jun-03 19:19:42.297 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/Users/olgabot/.nextflow/plugins; core-plugins: nf-amazon@2.5.2,nf-azure@1.6.0,nf-cloudcache@0.4.1,nf-codecommit@0.2.0,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2,nf-tower@1.9.1,nf-wave@1.4.2
Jun-03 19:19:42.310 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-03 19:19:42.312 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-03 19:19:42.315 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.10.0 in 'deployment' mode
Jun-03 19:19:42.329 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jun-03 19:19:42.400 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Jun-03 19:19:42.415 [main] DEBUG nextflow.cli.CmdRun - Launching `test.nf` [distracted_ardinghelli] DSL2 - revision: d035f3150e
Jun-03 19:19:42.417 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jun-03 19:19:42.417 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jun-03 19:19:42.479 [main] DEBUG nextflow.Session - Session UUID: 6fd543fb-8452-49ef-a83e-c4fd7407adcd
Jun-03 19:19:42.479 [main] DEBUG nextflow.Session - Run name: distracted_ardinghelli
Jun-03 19:19:42.480 [main] DEBUG nextflow.Session - Executor pool size: 16
Jun-03 19:19:42.489 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Jun-03 19:19:42.528 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 24.04.2 build 5914
  Created: 29-05-2024 06:19 UTC (28-05-2024 23:19 PDT)
  System: Mac OS X 14.4.1
  Runtime: Groovy 4.0.21 on OpenJDK 64-Bit Server VM 21+35
  Encoding: UTF-8 (UTF-8)
  Process: 39250@Olgas-MBP-2.attlocal.net [192.168.1.67]
  CPUs: 16 - Mem: 16 GB (70.3 MB) - Swap: 13 GB (1.6 GB) - Virtual threads ON
Jun-03 19:19:42.543 [main] DEBUG nextflow.Session - Work-dir: /Users/olgabot/code/nextflow-each-metadata-error/work [Mac OS X]
Jun-03 19:19:42.543 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /Users/olgabot/code/nextflow-each-metadata-error/bin
Jun-03 19:19:42.556 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jun-03 19:19:42.569 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jun-03 19:19:42.597 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jun-03 19:19:42.604 [main] DEBUG nextflow.util.CustomPoolFactory - Creating virtual thread pool
Jun-03 19:19:42.674 [main] DEBUG nextflow.Session - Session start
Jun-03 19:19:43.275 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jun-03 19:19:43.289 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /Users/olgabot/.nextflow/secrets/store.json
Jun-03 19:19:43.297 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@5f7eee96] - activable => nextflow.secret.LocalSecretsProvider@5f7eee96
Jun-03 19:19:43.489 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jun-03 19:19:43.489 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Jun-03 19:19:43.495 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Jun-03 19:19:43.515 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=16; memory=16 GB; capacity=16; pollInterval=100ms; dumpInterval=5m
Jun-03 19:19:43.518 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Jun-03 19:19:43.567 [main] DEBUG nextflow.processor.TaskProcessor - Creating *combiner* operator for each param(s) at index(es): [1]
Jun-03 19:19:43.598 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: test_each
Jun-03 19:19:43.598 [main] DEBUG nextflow.Session - Igniting dataflow network (3)
Jun-03 19:19:43.600 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > test_each
Jun-03 19:19:43.600 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > test_each
Jun-03 19:19:43.600 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_50d3b5d87ed7d429: /Users/olgabot/code/nextflow-each-metadata-error/test.nf
Jun-03 19:19:43.601 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Jun-03 19:19:43.601 [main] DEBUG nextflow.Session - Session await
Jun-03 19:19:43.715 [Actor Thread 15] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=test_each (4); work-dir=null
  error [nextflow.exception.ProcessUnrecoverableException]: Process `test_each (4)` script contains error(s)
Jun-03 19:19:43.740 [Actor Thread 15] ERROR nextflow.processor.TaskProcessor - Error executing process > 'test_each (4)'

Caused by:
  No such variable: path -- Check script 'test.nf' at line: 14


Source block:
  meta.number = number
  """
  touch ${path.simpleName}_${number}.md
  """

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Jun-03 19:19:43.763 [Actor Thread 15] DEBUG nextflow.Session - Session aborted -- Cause: Process `test_each (4)` script contains error(s)
Jun-03 19:19:43.780 [Actor Thread 15] DEBUG nextflow.Session - The following nodes are still active:
[process] test_each
  status=ACTIVE
  port 0: (queue) closed; channel: -
  port 1: (value) bound ; channel: __$eachinparam<1>
  port 2: (cntrl) -     ; channel: $

Jun-03 19:19:43.783 [main] DEBUG nextflow.Session - Session await > all processes finished
Jun-03 19:19:43.784 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jun-03 19:19:43.784 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Jun-03 19:19:43.785 [Actor Thread 7] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=test_each; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Jun-03 19:19:43.787 [Actor Thread 13] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=test_each (3); work-dir=null
  error [nextflow.exception.ProcessUnrecoverableException]: Process `test_each (3)` script contains error(s)
Jun-03 19:19:43.787 [Actor Thread 17] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=test_each (5); work-dir=null
  error [nextflow.exception.ProcessUnrecoverableException]: Process `test_each (5)` script contains error(s)
Jun-03 19:19:43.788 [Actor Thread 9] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=test_each (1); work-dir=null
  error [nextflow.exception.ProcessUnrecoverableException]: Process `test_each (1)` script contains error(s)
Jun-03 19:19:43.789 [Actor Thread 11] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=test_each (2); work-dir=null
  error [nextflow.exception.ProcessUnrecoverableException]: Process `test_each (2)` script contains error(s)
Jun-03 19:19:43.790 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Jun-03 19:19:43.974 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jun-03 19:19:43.990 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
